"""criação de banco de usuários

Revision ID: 556bff0c555c
Revises: 076ac858d778
Create Date: 2025-08-13 18:22:04.051582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556bff0c555c'
down_revision = '076ac858d778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
