"""empty message

Revision ID: 99d0b4df088d
Revises: f3cb7bc56dc9
Create Date: 2025-08-14 20:21:00.762129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d0b4df088d'
down_revision = 'f3cb7bc56dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_destino', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email_usuario', sa.String(), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('email_usuario')
        batch_op.drop_column('email_destino')

    # ### end Alembic commands ###
