"""empty message

Revision ID: f3cb7bc56dc9
Revises: 8096f8d55127
Create Date: 2025-08-14 13:31:42.256729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cb7bc56dc9'
down_revision = '8096f8d55127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.String(), nullable=True))
        batch_op.drop_column('mensagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensagem', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###
